#include <iostream>
#include <fstream>
#include <sstream>
#include <string>
#include <vector>
#include <array>
#include <map>
#include <regex>
#include <algorithm>
#include <set>
#include <memory>
#include <stack>